from django.contrib import admin
from .models import *

admin.site.register(Info)
admin.site.register(NewsCategory)
admin.site.register(New)
admin.site.register(Team)
admin.site.register(Tournament)
admin.site.register(Match)
admin.site.register(Rating)
admin.site.register(VideoBanner)
admin.site.register(Position)
admin.site.register(Player)
admin.site.register(Stadium)
admin.site.register(Sponsor)
admin.site.register(NewsBanner)
admin.site.register(TeamBanner)
admin.site.register(ManagementBanner)
admin.site.register(Coach)
admin.site.register(Management)
admin.site.register(ClubBanner)
admin.site.register(ClubPagePost)
admin.site.register(AcademyPagePost)
admin.site.register(AcademyBanner)
admin.site.register(Product)
admin.site.register(ProductImage)