# Generated by Django 4.1.6 on 2023-11-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_match_first_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
