# Generated by Django 4.1.6 on 2023-11-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_match_second_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingPlaces',
            new_name='Rating',
        ),
    ]
