# Generated by Django 4.1.6 on 2023-11-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_ratingplaces_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.team'),
        ),
    ]
