# Generated by Django 4.1.6 on 2023-11-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_match_first_team_alter_match_second_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='mini_title',
        ),
    ]
