# Generated by Django 4.1.6 on 2023-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
