# Generated by Django 4.1.6 on 2023-11-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_match_ticket_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
