# Generated by Django 4.1.6 on 2023-11-09 12:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clubpagepost_remove_achievementtext_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Text Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutAcademy',
        ),
        migrations.DeleteModel(
            name='AcademyGallery',
        ),
    ]
