# Generated by Django 4.1.6 on 2023-11-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_academypagepost_delete_aboutacademy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCollage',
        ),
    ]
