# Generated by Django 4.1.6 on 2023-11-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_address_stadium_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='text',
        ),
    ]
